# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_SEC_DEBUG) += sec_debug.o sec_crashkey.o \
			   sec_key_notifier.o \
			   sec_debug_partition.o \
			   sec_crashkey_user.o
obj-$(CONFIG_SEC_DEBUG_SCHED_LOG) += sec_debug_sched_log.o
obj-$(CONFIG_USER_RESET_DEBUG) += sec_debug_user_reset.o
obj-$(CONFIG_SEC_DEBUG_FORCE_ERROR) += sec_debug_force_err.o
obj-$(CONFIG_SEC_DEBUG_DOUBLE_FREE) += sec_debug-dfd.o
obj-$(CONFIG_SEC_DEBUG_SUMMARY) += sec_debug_summary.o
obj-$(CONFIG_SEC_NAD)		+= sec_nad.o
obj-$(CONFIG_SEC_NAD)		+= spinlock_test.o
obj-$(CONFIG_SEC_DEBUG_GAF_V4)		+= sec_gaf_v4.o
