obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)	+= sensors_class.o
obj-$(CONFIG_SENSORS_CM36672P_IRIS)	+= cm36672p_iris.o
obj-$(CONFIG_SENSORS_HRMSENSOR)		+= hrmsensor.o
obj-$(CONFIG_SENSORS_HRM_MAX86915)	+= hrm_max86915.o
obj-$(CONFIG_SENSORS_MAX86915)		+= max86915.o
obj-$(CONFIG_SENSORS_SX9320)		+= sx9320.o