#
#  makefile for tspdrv kernel module
#

obj-$(CONFIG_MOTOR_DRV_SM5720)		+= sm5720_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77705)	+= max77705_haptic.o
obj-$(CONFIG_SS_VIBRATOR)		+= ss_vibrator.o
obj-$(CONFIG_BLDC_VIBRATOR)		+= bldc_vibrator.o
