ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += cam_ois_dev.o cam_ois_core.o cam_ois_soc.o
obj-$(CONFIG_SAMSUNG_OIS_RUMBA_S4) += cam_ois_rumba_s4.o cam_ois_thread.o
obj-$(CONFIG_SAMSUNG_OIS_RUMBA_S6) += cam_ois_rumba_s6.o cam_ois_thread.o
obj-$(CONFIG_SAMSUNG_OIS_MCU_STM32) += cam_ois_mcu_stm32g.o cam_ois_thread.o
