
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_LSM6DSL_FACTORY) += lsm6dsl_accel.o lsm6dsl_gyro.o
obj-$(CONFIG_AK09916C_FACTORY) += ak09916c_mag.o
obj-$(CONFIG_LPS22HB_FACTORY) += lps22hb_pressure.o
obj-$(CONFIG_TMD490X_FACTORY) += tmd490x_light.o tmd490x_prox.o
obj-$(CONFIG_SUPPORT_MOBEAM) += tmd490x_barcode_emul.o
obj-$(CONFIG_SUPPORT_HIDDEN_HOLE) += hidden_hole.o
