#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging
ccflags-y += -Idrivers/gpu/drm/msm/sde
ccflags-y += -Idrivers/gpu/drm/msm/samsung

obj-y  += ss_dsi_panel_S6E3HA6_AMS622MR01.o
obj-y  += ss_dsi_smart_dimming_S6E3HA6_AMS622MR01.o
