dtb-$(CONFIG_SEC_STARQLTE_PROJECT) += sdm845-sec-starqlte-r00.dtb	\
			sdm845-sec-starqlte-r01.dtb			\
			sdm845-sec-starqlte-r02.dtb			\
			sdm845-sec-starqlte-r03.dtb			\
			sdm845-sec-starqlte-r04.dtb			\
			sdm845-sec-starqlte-r05.dtb			\
			sdm845-sec-starqlte-r06.dtb			\
			sdm845-sec-starqlte-r07.dtb			\
			sdm845-sec-starqlte-r08.dtb			\
			sdm845-sec-starqlte-r09.dtb			\
			sdm845-sec-starqlte-r10.dtb			\
			sdm845-sec-starqlte-r11.dtb			\
			sdm845-sec-starqlte-r12.dtb			\
			sdm845-sec-starqlte-r12_v2.1.dtb		\
			sdm845-sec-starqlte-r13.dtb			\
			sdm845-sec-starqlte-r14.dtb

dtb-$(CONFIG_SEC_STAR2QLTE_PROJECT) += sdm845-sec-star2qlte-r00.dtb	\
			sdm845-sec-star2qlte-r01.dtb			\
			sdm845-sec-star2qlte-r02.dtb			\
			sdm845-sec-star2qlte-r03.dtb			\
			sdm845-sec-star2qlte-r04.dtb			\
			sdm845-sec-star2qlte-r05.dtb			\
			sdm845-sec-star2qlte-r06.dtb			\
			sdm845-sec-star2qlte-r07.dtb			\
			sdm845-sec-star2qlte-r08.dtb			\
			sdm845-sec-star2qlte-r09.dtb			\
			sdm845-sec-star2qlte-r10.dtb			\
			sdm845-sec-star2qlte-r11.dtb			\
			sdm845-sec-star2qlte-r12.dtb			\
			sdm845-sec-star2qlte-r12_v2.1.dtb		\
			sdm845-sec-star2qlte-r13.dtb			\
			sdm845-sec-star2qlte-r14.dtb

dtb-$(CONFIG_SEC_CROWNQLTE_PROJECT) += sdm845-sec-crownqlte-r00.dtb	\
			sdm845-sec-crownqlte-r01.dtb 			\
			sdm845-sec-crownqlte-r02.dtb			\
			sdm845-sec-crownqlte-r03.dtb			\
			sdm845-sec-crownqlte-r04.dtb			\
			sdm845-sec-crownqlte-r05.dtb			\
			sdm845-sec-crownqlte-r06.dtb			\
			sdm845-sec-crownqlte-r10.dtb

dtb-$(CONFIG_SEC_LYKANLTE_PROJECT) += sdm845-sec-lykanlte-r00.dtb	\
			sdm845-sec-lykanlte-r01.dtb

ifeq ($(filter y,$(CONFIG_MACH_STARQLTE_CHNZC) $(CONFIG_MACH_STARQLTE_CHNZM) $(CONFIG_MACH_STARQLTE_CHN_LDU)),y)
dtb-y = sdm845-sec-starqlte-chn-r02.dtb		\
	sdm845-sec-starqlte-chn-r03.dtb		\
	sdm845-sec-starqlte-chn-r04.dtb		\
	sdm845-sec-starqlte-chn-r05.dtb		\
	sdm845-sec-starqlte-chn-r06.dtb		\
	sdm845-sec-starqlte-chn-r07.dtb		\
	sdm845-sec-starqlte-chn-r08.dtb		\
	sdm845-sec-starqlte-chn-r09.dtb		\
	sdm845-sec-starqlte-chn-r10.dtb		\
	sdm845-sec-starqlte-chn-r11.dtb		\
	sdm845-sec-starqlte-chn-r12.dtb		\
	sdm845-sec-starqlte-chn-r13.dtb		\
	sdm845-sec-starqlte-chn-r13_v2.1.dtb	\
	sdm845-sec-starqlte-chn-r14.dtb		\
	sdm845-sec-starqlte-chn-r14_v2.1.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_STAR2QLTE_CHNZC) $(CONFIG_MACH_STAR2QLTE_CHN_LDU)),y)
dtb-y = sdm845-sec-star2qlte-chn-r02.dtb	\
	sdm845-sec-star2qlte-chn-r03.dtb	\
	sdm845-sec-star2qlte-chn-r04.dtb	\
	sdm845-sec-star2qlte-chn-r05.dtb	\
	sdm845-sec-star2qlte-chn-r06.dtb	\
	sdm845-sec-star2qlte-chn-r07.dtb	\
	sdm845-sec-star2qlte-chn-r08.dtb	\
	sdm845-sec-star2qlte-chn-r09.dtb	\
	sdm845-sec-star2qlte-chn-r10.dtb	\
	sdm845-sec-star2qlte-chn-r11.dtb	\
	sdm845-sec-star2qlte-chn-r12.dtb	\
	sdm845-sec-star2qlte-chn-r13.dtb	\
	sdm845-sec-star2qlte-chn-r13_v2.1.dtb	\
	sdm845-sec-star2qlte-chn-r14.dtb	\
	sdm845-sec-star2qlte-chn-r14_v2.1.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_STARQLTE_CHNHK)),y)
dtb-y = sdm845-sec-starqlte-chnhk-r02.dtb		\
	sdm845-sec-starqlte-chnhk-r03.dtb		\
	sdm845-sec-starqlte-chnhk-r04.dtb		\
	sdm845-sec-starqlte-chnhk-r05.dtb		\
	sdm845-sec-starqlte-chnhk-r06.dtb		\
	sdm845-sec-starqlte-chnhk-r07.dtb		\
	sdm845-sec-starqlte-chnhk-r08.dtb		\
	sdm845-sec-starqlte-chnhk-r09.dtb		\
	sdm845-sec-starqlte-chnhk-r10.dtb		\
	sdm845-sec-starqlte-chnhk-r11.dtb		\
	sdm845-sec-starqlte-chnhk-r12.dtb		\
	sdm845-sec-starqlte-chnhk-r13.dtb		\
	sdm845-sec-starqlte-chnhk-r13_v2.1.dtb		\
	sdm845-sec-starqlte-chnhk-r14.dtb		\
	sdm845-sec-starqlte-chnhk-r14_v2.1.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_STAR2QLTE_CHNHK)),y)
dtb-y = sdm845-sec-star2qlte-chnhk-r02.dtb	\
	sdm845-sec-star2qlte-chnhk-r03.dtb	\
	sdm845-sec-star2qlte-chnhk-r04.dtb	\
	sdm845-sec-star2qlte-chnhk-r05.dtb	\
	sdm845-sec-star2qlte-chnhk-r06.dtb	\
	sdm845-sec-star2qlte-chnhk-r07.dtb	\
	sdm845-sec-star2qlte-chnhk-r08.dtb	\
	sdm845-sec-star2qlte-chnhk-r09.dtb	\
	sdm845-sec-star2qlte-chnhk-r10.dtb	\
	sdm845-sec-star2qlte-chnhk-r11.dtb	\
	sdm845-sec-star2qlte-chnhk-r12.dtb	\
	sdm845-sec-star2qlte-chnhk-r13.dtb	\
	sdm845-sec-star2qlte-chnhk-r13_v2.1.dtb	\
	sdm845-sec-star2qlte-chnhk-r14.dtb	\
	sdm845-sec-star2qlte-chnhk-r14_v2.1.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_STARQLTE_DCM) $(CONFIG_MACH_STARQLTE_KDI)),y)
dtb-y = sdm845-sec-starqlte-jpn-r05.dtb	\
	sdm845-sec-starqlte-jpn-r06.dtb \
	sdm845-sec-starqlte-jpn-r07.dtb \
	sdm845-sec-starqlte-jpn-r08.dtb	\
	sdm845-sec-starqlte-jpn-r09.dtb \
	sdm845-sec-starqlte-jpn-r10.dtb	\
	sdm845-sec-starqlte-jpn-r11.dtb	\
	sdm845-sec-starqlte-jpn-r12.dtb	\
	sdm845-sec-starqlte-jpn-r13.dtb	\
	sdm845-sec-starqlte-jpn-r14.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_STAR2QLTE_DCM) $(CONFIG_MACH_STAR2QLTE_KDI)),y)
dtb-y = sdm845-sec-star2qlte-jpn-r05.dtb	\
	sdm845-sec-star2qlte-jpn-r06.dtb	\
	sdm845-sec-star2qlte-jpn-r07.dtb	\
	sdm845-sec-star2qlte-jpn-r08.dtb	\
	sdm845-sec-star2qlte-jpn-r09.dtb	\
	sdm845-sec-star2qlte-jpn-r10.dtb	\
	sdm845-sec-star2qlte-jpn-r11.dtb	\
	sdm845-sec-star2qlte-jpn-r12.dtb	\
	sdm845-sec-star2qlte-jpn-r13.dtb	\
	sdm845-sec-star2qlte-jpn-r14.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_CROWNQLTE_CHNZC) $(CONFIG_MACH_CROWNQLTE_CHNZM) $(CONFIG_MACH_CROWNQLTE_CHN_LDU)),y)
dtb-y =	sdm845-sec-crownqlte-chn-r03.dtb	\
	sdm845-sec-crownqlte-chn-r05.dtb	\
	sdm845-sec-crownqlte-chn-r06.dtb	\
	sdm845-sec-crownqlte-chn-r10.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_CROWNQLTE_CHNHK)),y)
dtb-y =	sdm845-sec-crownqlte-chnhk-r03.dtb	\
	sdm845-sec-crownqlte-chnhk-r05.dtb	\
	sdm845-sec-crownqlte-chnhk-r06.dtb	\
	sdm845-sec-crownqlte-chnhk-r10.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_CROWNQLTE_DCM) $(CONFIG_MACH_CROWNQLTE_KDI)),y)
dtb-y = sdm845-sec-crownqlte-jpn-r03.dtb	
endif

ifeq ($(filter y,$(CONFIG_MACH_LYKANLTE_CHNZC)),y)
dtb-y =	sdm845-sec-lykanlte-chn-r00.dtb		\
	sdm845-sec-lykanlte-chn-r01.dtb
endif

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/../,$(dtb-y))
endif
clean-files := *.dtb *.reverse.dts

