ccflags-y += -Idrivers/media/platform/msm/camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_ois
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_eeprom
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_actuator
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_aperture

obj-$(CONFIG_SPECTRA_CAMERA) +=  cam_sensor_util.o cam_sysfs_init.o
