# drivers/staging/samsung/Makefile
#
# Copyright (c) 2010-2011 Samsung Electronics Co., Ltd.
#		http://www.samsung.com/
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Samsung sec sysfs Feature
obj-$(CONFIG_SEC_FD_DETECT) += sec_fd_detect.o

# Samsung TN Heavy Cpu Count
obj-$(CONFIG_SEC_HEAVY_TASK_CPU)		+= sec_heavy_task_cpu.o

# Samsung HQM device feature
obj-$(CONFIG_SEC_HQM_DEVICE)		+= sec_hqm_device.o