#
# Makefile for the kernel character device drivers.
#
obj-$(CONFIG_ISDBT_FC83X7_SPI) += fc83x7_spi/
obj-$(CONFIG_ISDBT_FC8350_SPI) += fc8350_spi/
obj-$(CONFIG_ISDBT_FC8300_SPI) += fc8300_spi/
obj-$(CONFIG_ISDBT_FC8180_SPI) += fc8180_spi/
